# Generated by Django 6.1 on 2026-08-17 02:48

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_token', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response_status', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usages',
                'ordering': ['-request_timestamp'],
            },
        ),
    ]
