# Generated by Django 6.1 on 2026-08-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_usercredit_frozen_prepaid_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='low_credit_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
