# Generated by Django 6.1 on 2026-08-19 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_usercredit_low_credit_alert_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUsageCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid')], max_length=16)),
                ('gpu', models.CharField(max_length=128)),
                ('hours_consumed', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('total_consumption', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cycle_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cycle_ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Usage Cycle',
                'verbose_name_plural': 'Client Usage Cycles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'is_active'], name='billing_cli_client__18bfe9_idx')],
            },
        ),
    ]
