# Generated by Django 6.1 on 2026-08-17 02:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('vram_capacity_gb', models.PositiveIntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'GPU Model',
                'verbose_name_plural': 'GPU Models',
                'ordering': ['-price_per_hour'],
            },
        ),
        migrations.CreateModel(
            name='GPUInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LEASED', 'Leased'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=16)),
                ('is_dedicated', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='leases.gpumodel')),
            ],
            options={
                'verbose_name': 'GPU Instance',
                'verbose_name_plural': 'GPU Instances',
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vram_used_gb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('compute_load_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_thermal_alert', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('gpu_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='leases.gpuinstance')),
            ],
            options={
                'verbose_name': 'Metric Snapshot',
                'verbose_name_plural': 'Metric Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RentalLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('TERMINATING', 'Terminating'), ('COMPLETED', 'Completed'), ('SUSPENDED_PAYMENT', 'Suspended - Payment')], default='PROVISIONING', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_billed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volume_discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('gpu_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='leases.gpuinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Lease',
                'verbose_name_plural': 'Rental Leases',
            },
        ),
        migrations.AddIndex(
            model_name='gpuinstance',
            index=models.Index(fields=['status', 'is_dedicated'], name='leases_gpui_status_e333a2_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['gpu_instance', 'timestamp'], name='leases_metr_gpu_ins_7fa510_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallease',
            index=models.Index(fields=['status', 'started_at'], name='leases_rent_status_f7ae7d_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallease',
            index=models.Index(fields=['user', 'status'], name='leases_rent_user_id_e5f3a4_idx'),
        ),
    ]
